name: sync from s3 bucket

on:
  schedule:
  - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - uses: cachix/install-nix-action@8887e596b4ee1134dae06b98d573bd674693f47c
    - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b
    - name: update
      run: |
        nix run
        git status
